### ISSUE TITLE
Добавить команде /chatcolor возможность менять другому игроку

### ISSUE THREAD

**Issue by KungfuEpt** [Flectone/FlectoneChat#14]
Команда: /chatcolor <цвет1> <цвет2> <игрок>
Право: flectonechat.chatcolor.other

**Comment by TheFaser** [comment]
А зачем?

**Comment by KungfuEpt** [comment]
А зачем тогда добавлять команду /chatcolor? Благодаря данной возможности, можно сделать готовые шаблоны палитр для чата благодаря того же DeluxeMenus.

**Comment by TheFaser** [comment]
Окей, понял, будет сделано

**Comment by TheFaser** [comment]
https://github.com/Flectone/FlectoneChat/commit/237f013c8fe164f49938e0b55b49e37552924b37
Сделал, в некст релизе будет
