### ISSUE TITLE
Не работает чат после удаления плагина

### ISSUE THREAD

**Issue by vuwWolf** [Flectone/FlectoneChat#2]
После удаления FlectoneChat на моём сервере перестал работать чат в принципе, не отображается ни одно сообщение.

**Comment by TheFaser** [comment]
FlectoneChat никак не может сломать чат после удаления, потому что он взаимодействует с сообщением только при его отправке. Скинь полностью список плагинов, возможно у тебя какой-то из них ломает чат

**Comment by vuwWolf** [comment]
![image](https://user-images.githubusercontent.com/63950114/226103248-73efa5cf-2966-423f-b757-f797a2e98305.png)

**Comment by TheFaser** [comment]
сейчас у тебя установлен FlectoneChat и Essentials они могут конфликтовать вместе. Если удалишь FlectoneChatЮ то эссеншиал должен работать и делать свой чат, посмотри у него в конфигах

**Comment by vuwWolf** [comment]
Для того, чтобы Essentials менял чат, нужен ещё EssentialsX Chat. А ещё, мне нужен сам Essentials для запрета спавна визера. Я хотел заменить FlectoneChat, но в итоге другой плагин на чат работал некорректно, сообщения игроков просто не показывались

**Comment by TheFaser** [comment]
Так может проблема в другом плагине чата, а не во флектон-чате? Флектон чат работает только в момент захода игрока и полная перезагрузка с его удалением, очистит от всего что делал он
