### ISSUE TITLE
Отключается при запуске

### ISSUE THREAD

**Issue by Smertomish** [Flectone/FlectoneChat#20]
![изображение_2023-08-28_201551592](https://github.com/Flectone/FlectoneChat/assets/87101891/c907cd0f-544d-4a7b-8fa0-9278fcc09f5b)

Вылезает такая ошибка в консоли и плагин выключается. Ничего в конфиге не трогал

**Comment by Smertomish** [comment]
в дискорде хотел обратиться, но там нужно двухфакторка через смс, а номер телефона не привязывается

**Comment by TheFaser** [comment]
В новом релизе 3.10.0 будет фикс, сегодня-завтра получается он выйдет

**Comment by TheFaser** [comment]
> в дискорде хотел обратиться, но там нужно двухфакторка через смс, а номер телефона не привязывается

Скажи свой ник, я пропущу твой ник дискорду

**Comment by Smertomish** [comment]
smertomish, большое спасибо за быстрый ответ!

**Comment by TheFaser** [comment]
> smertomish, большое спасибо за быстрый ответ!

Подтвердил
