### ISSUE TITLE
FlectoneChat 1.20.2 purpur issue

### ISSUE THREAD

**Issue by Rivers071** [Flectone/FlectoneChat#23]
proof: https://mclo.gs/kWyqIWo
When i tried to login in 1.20.2 version with the FlectoneChat enable, my client showed this error:

![Captura de tela 2023-10-27 225413](https://github.com/Flectone/FlectoneChat/assets/68114271/6812fe5f-fb35-4e6f-8fba-75e548dcee08)

**Comment by TheFaser** [comment]
To fix this, turn off the server.brand setting in config.yml. This problem is common and at the moment we are trying to understand what exactly it is related to, because it does not happen on all servers.
