### ISSUE TITLE
[enhancement] AFKTimeoutModule send empty text

### ISSUE THREAD

**Issue by CrazyWords1** [Flectone/FlectoneChat#24]
At the moment, if you write "afk messages" empty in the config it sends an empty string, would like to be able to customize this. 
Or to do at least like this:
```java
        if (!afkMessage.isEmpty()){
            player.sendMessage(MessageUtil.formatAll(player, MessageUtil.formatPlayerString(player, afkMessage)));
        }
```

**Comment by CrazyWords1** [comment]
enhancement about the beta version

**Comment by TheFaser** [comment]
Added - https://github.com/Flectone/FlectoneChat/commit/b8766eed8e66e466ac672edd649992cd8c89a69b
