### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by Vinellon** [Flectone/FlectoneChat#4]
Было бы чудесно, чтобы этот плагин смог поддерживать papi, ведь сейчас это сильно завязывает руки.

**Comment by TheFaser** [comment]
В ближайших обновлениях попробую внести поддержку papi

**Comment by TheFaser** [comment]
@Vinellon, в релизе 3.3.2 добавил поддержку PAPI из конфигов, скажи если всё окей, то закрою эту ветку

**Comment by Vinellon** [comment]
> @Vinellon, в релизе 3.3.2 добавил поддержку PAPI из конфигов, скажи если всё окей, то закрою эту ветку

Да, вроде всё работает без проблем
